{
  "formatVersion": "1.1",
  "component": {
    "group": "io.coil-kt.coil3",
    "module": "coil-network-core",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-core-metadata-3.4.0-SNAPSHOT.jar",
          "url": "coil-network-core-3.4.0-SNAPSHOT.jar",
          "size": 12407,
          "sha512": "c590b836b18711f804aa97673c76ff0772f9c802b898c198336a754655ebf7a6d90f1a78a86c5767d6614cff531d8b7785b1416259faa3d5e891a8d469be75c9",
          "sha256": "7f2213b3588d73aed56d5e641c25b629a99b39fb0e1a753c3b66fbe0e964cabb",
          "sha1": "a1a3650f63e9a62ab201dd7a52450c72bf7f5e3f",
          "md5": "6540a533fccaaeae49220264d95d627b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "coil-network-core-kotlin-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-network-core-3.4.0-SNAPSHOT-sources.jar",
          "size": 12216,
          "sha512": "1108e43814f6d40944831cf30f8a993499e5ab7bc4beadd862ff5734b9a53fbfb92275680bbc86cca0dc23a396fd6ea30b612f49b4924c92bd1bc80ca2900842",
          "sha256": "b0d9d5fac7c46ff6c5fb04ce66ddb0a474d3e5168376a1a88056ab15ef5928fd",
          "sha1": "4958e903d485c845e06ab52462dfce77f3a35d1d",
          "md5": "f60cac69c1e20e7d86e82edd85636ed1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-network-core-android/3.4.0-SNAPSHOT/coil-network-core-android-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-android",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-network-core-android/3.4.0-SNAPSHOT/coil-network-core-android-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-android",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-network-core-android/3.4.0-SNAPSHOT/coil-network-core-android-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-android",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-iosarm64/3.4.0-SNAPSHOT/coil-network-core-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-iosarm64/3.4.0-SNAPSHOT/coil-network-core-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-iosarm64/3.4.0-SNAPSHOT/coil-network-core-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-iossimulatorarm64/3.4.0-SNAPSHOT/coil-network-core-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-iossimulatorarm64/3.4.0-SNAPSHOT/coil-network-core-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-iossimulatorarm64/3.4.0-SNAPSHOT/coil-network-core-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-iosx64/3.4.0-SNAPSHOT/coil-network-core-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-iosx64/3.4.0-SNAPSHOT/coil-network-core-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-iosx64/3.4.0-SNAPSHOT/coil-network-core-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-network-core-js/3.4.0-SNAPSHOT/coil-network-core-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-network-core-js/3.4.0-SNAPSHOT/coil-network-core-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-network-core-js/3.4.0-SNAPSHOT/coil-network-core-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-network-core-jvm/3.4.0-SNAPSHOT/coil-network-core-jvm-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-jvm",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-network-core-jvm/3.4.0-SNAPSHOT/coil-network-core-jvm-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-jvm",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-network-core-jvm/3.4.0-SNAPSHOT/coil-network-core-jvm-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-jvm",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-linuxarm64/3.4.0-SNAPSHOT/coil-network-core-linuxarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-linuxarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-linuxarm64/3.4.0-SNAPSHOT/coil-network-core-linuxarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-linuxarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-linuxx64/3.4.0-SNAPSHOT/coil-network-core-linuxx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-linuxx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-linuxx64/3.4.0-SNAPSHOT/coil-network-core-linuxx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-linuxx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-macosarm64/3.4.0-SNAPSHOT/coil-network-core-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-macosarm64/3.4.0-SNAPSHOT/coil-network-core-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-macosarm64/3.4.0-SNAPSHOT/coil-network-core-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-macosx64/3.4.0-SNAPSHOT/coil-network-core-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-macosx64/3.4.0-SNAPSHOT/coil-network-core-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-core-macosx64/3.4.0-SNAPSHOT/coil-network-core-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-network-core-wasm-js/3.4.0-SNAPSHOT/coil-network-core-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-network-core-wasm-js/3.4.0-SNAPSHOT/coil-network-core-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-network-core-wasm-js/3.4.0-SNAPSHOT/coil-network-core-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-core-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    }
  ]
}
