{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-network-core/3.4.0-SNAPSHOT/coil-network-core-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-network-core",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-core-wasm-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-network-core-wasm-js-3.4.0-SNAPSHOT.klib",
          "size": 3441418,
          "sha512": "78d9ce193244e99e0a77573f4dbd5614605de0c49629121e98ececbb87416088f041210d1d51f8fd7530bd49d0437cb422215fa70ee5dd3bd05734502bd100fa",
          "sha256": "57a26829a249f7eaa7786fb843665ddf2207dbfb235ae0ce274b861b373fa93c",
          "sha1": "ae9b13123cfccbe1c543944cfccd0ab9bd64fd4f",
          "md5": "97fb36237f9e356ecaa8562720366455"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-core-wasm-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-network-core-wasm-js-3.4.0-SNAPSHOT.klib",
          "size": 3441418,
          "sha512": "78d9ce193244e99e0a77573f4dbd5614605de0c49629121e98ececbb87416088f041210d1d51f8fd7530bd49d0437cb422215fa70ee5dd3bd05734502bd100fa",
          "sha256": "57a26829a249f7eaa7786fb843665ddf2207dbfb235ae0ce274b861b373fa93c",
          "sha1": "ae9b13123cfccbe1c543944cfccd0ab9bd64fd4f",
          "md5": "97fb36237f9e356ecaa8562720366455"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "coil-network-core-wasm-js-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-network-core-wasm-js-3.4.0-SNAPSHOT-sources.jar",
          "size": 12216,
          "sha512": "8dd5765f642666e938ada828ff88f9647e3bb3cdc75406547c0a778313500274fe2dc572d8b636ef62b5e9e90242eb771ab50989a32b1936c2a96694555a7ea6",
          "sha256": "9b39dc835f2f8d7c6fd08619b1cd3328e130e01aedf583ad19c2b97888eb7935",
          "sha1": "4a2ddfc3e84a716218e63ef75b2b994e12fc3350",
          "md5": "b28124cf8eade53422542a4dbeeba485"
        }
      ]
    }
  ]
}
