{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-network-ktor3/3.4.0-SNAPSHOT/coil-network-ktor3-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-network-ktor3",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-ktor3-release.aar",
          "url": "coil-network-ktor3-android-3.4.0-SNAPSHOT.aar",
          "size": 23332,
          "sha512": "b07ec3f2cc741c07e5d5c4e7021c1932be5003e3c42ed3993a6685198e932aad798de08a08dd6c968aa9b6884755272838593336a593196ecd0820a5b3b0c0a3",
          "sha256": "2552af9a88eb01b7b9b1b06ce2b2620b35da4ad1cf58e2d5f37dbdc052d24356",
          "sha1": "3939510485b6b11549bb6ed053346bff0cf2158f",
          "md5": "89f1048e81307287378a1e0903544ef0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "coil-network-ktor3-release.aar",
          "url": "coil-network-ktor3-android-3.4.0-SNAPSHOT.aar",
          "size": 23332,
          "sha512": "b07ec3f2cc741c07e5d5c4e7021c1932be5003e3c42ed3993a6685198e932aad798de08a08dd6c968aa9b6884755272838593336a593196ecd0820a5b3b0c0a3",
          "sha256": "2552af9a88eb01b7b9b1b06ce2b2620b35da4ad1cf58e2d5f37dbdc052d24356",
          "sha1": "3939510485b6b11549bb6ed053346bff0cf2158f",
          "md5": "89f1048e81307287378a1e0903544ef0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "coil-network-ktor3-android-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-network-ktor3-android-3.4.0-SNAPSHOT-sources.jar",
          "size": 4083,
          "sha512": "a64da74b97e87c9476c77718701aa6838095f007571f6c849916e8517a8365a0f62ab9d1a811828ace54ff20593d676ec7585983f13f4fa0aa50ffd2fe3f9bad",
          "sha256": "8f1a55a9ed282fe77df261aa7e4d57172508a70843951af422cfcbf97e0ab349",
          "sha1": "fe05b74c1f7dcea73834ab506067dc1374495622",
          "md5": "e030b1372f084a04be95a0d2599fa7fa"
        }
      ]
    }
  ]
}
