{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-compose/3.4.0-SNAPSHOT/coil-compose-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-compose",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-compose-js-3.4.0-SNAPSHOT.klib",
          "size": 3407533,
          "sha512": "e5642fdacd2c5967f0fc174c64eaa10f93057b8f5dc7ea1fbc134e86c562c5c8809229b375b20c16b8e42ca36ba7f3901c6212afde204fd82cfaebcaf50717c9",
          "sha256": "b0bf3b6f456844685cc823dd02ee3d07b124ad7ccf3b82345fd950f567ecc601",
          "sha1": "6153d356a427fae33311bdcabaa332cb66552562",
          "md5": "5a0c51789d09aaf605c5ccc4de2d82ad"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-compose-js-3.4.0-SNAPSHOT.klib",
          "size": 3407533,
          "sha512": "e5642fdacd2c5967f0fc174c64eaa10f93057b8f5dc7ea1fbc134e86c562c5c8809229b375b20c16b8e42ca36ba7f3901c6212afde204fd82cfaebcaf50717c9",
          "sha256": "b0bf3b6f456844685cc823dd02ee3d07b124ad7ccf3b82345fd950f567ecc601",
          "sha1": "6153d356a427fae33311bdcabaa332cb66552562",
          "md5": "5a0c51789d09aaf605c5ccc4de2d82ad"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "coil-compose-js-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-compose-js-3.4.0-SNAPSHOT-sources.jar",
          "size": 5476,
          "sha512": "76f78fc8e21ba26fdfba4d78d66dfc3aa89d029798d19807718b8f4d0c62b7264e903bfc67e45d2cad11dab5ccefffec2fe01e9177edd4c21421fd29b9e20f2d",
          "sha256": "31174b39d8ac98c986533e3f82cc62a5be244fee3d44dcf00f249e7d1849650a",
          "sha1": "c0579e5ea19c4eedf6aa44379d0add2f7436ec73",
          "md5": "a43398b8e04292f126e5158abd6b3267"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-3.4.0-SNAPSHOT.kotlin_resources.zip",
          "url": "coil-compose-js-3.4.0-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 346,
          "sha512": "4d5532c17b1d0b466e4c38167a35ce4db1653ace34dfe8af82d131b0bb227400d5063859e9cea7ee30fc71b47c7f67c9b9203b7a2dac241ab0589c7b8ae4a256",
          "sha256": "80c359f106560e250b68108a8ced4fe0f671464afad996d672a9d99a8d785d62",
          "sha1": "970241470787400573f274d40bd0ff3e8445fe37",
          "md5": "9d2bc257a7e0574f9de4d612d6303937"
        }
      ]
    }
  ]
}
