{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil/3.4.0-SNAPSHOT/coil-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-macosArm64Main-3.4.0-SNAPSHOT.klib",
          "url": "coil-macosarm64-3.4.0-SNAPSHOT.klib",
          "size": 11338,
          "sha512": "eec307dcddf4e68e33af2cde054ae9bc2ee76d044b9ace114d90a2b6151adc8289b03ef7f995cc075fcfd11173d98998974d331b9579c569abef786be564b5ab",
          "sha256": "c631e3fcf7ae94a5b23eb6c866ea8e81b06f1cf3ec32d254232f8e012b7b21db",
          "sha1": "08630bd3c231902135fcf66d3a198d2f45cd26c7",
          "md5": "c0e4ed7f82bea642408c7ce8ea7f557c"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "coil-macosarm64-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-macosarm64-3.4.0-SNAPSHOT-sources.jar",
          "size": 2422,
          "sha512": "1b2c21550919e28e49987eca446d93cb0437747e9faa0ef498cc94095da08978134a938d40ff150175aa16aff2b482c05e744c25cbe1e15d83aea25512e24f3c",
          "sha256": "5cb583ff59b7ddcbfc8a765ab62c174475dfa2c292c25101073ec4ef77867ebd",
          "sha1": "c2e2eb9f948f34422b4ab1fdd782c2c1c1dcb468",
          "md5": "3a8989ae151f9cac0bc7d1c625025659"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-macosarm64-3.4.0-SNAPSHOT-metadata.jar",
          "url": "coil-macosarm64-3.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
