{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-compose-core/3.4.0-SNAPSHOT/coil-compose-core-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-compose-core",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-core-iosArm64Main-3.4.0-SNAPSHOT.klib",
          "url": "coil-compose-core-iosarm64-3.4.0-SNAPSHOT.klib",
          "size": 154560,
          "sha512": "bef238dae60f5368584de5e932876d81e2195e6877932c8c23212508cf3468c1acb8734d1190320b3ab9f956829a5cd70a6ac9a564743e3b6e84d3f553ea1c70",
          "sha256": "d46e04288b1e9e85d02a2d55a03290c03edddd3a1b9c07e6dd1b158103f2a570",
          "sha1": "e1bf1a9665c48fcd720e876c3d017fc5eeefe59a",
          "md5": "feeccbd7e53afd9828f60cfe7ccac732"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "coil-compose-core-iosarm64-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-compose-core-iosarm64-3.4.0-SNAPSHOT-sources.jar",
          "size": 26307,
          "sha512": "16318c4080d8e72489d108f8451b01a802547e1b3bf2a6ce8e167004a441d7100b90f8d85bbee0c96346f8c94eeb4f292c7ff41186a242ef4741e63058a3472e",
          "sha256": "1197a1d8da6444937acdc166825bc8fecd4f1834238706469019b6ad023c0a64",
          "sha1": "3c767bc9c24ad6da7c7cbd61cb21a4eabc5e8169",
          "md5": "d711e9e948bae7fc8078feb809a0b611"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-core-3.4.0-SNAPSHOT.kotlin_resources.zip",
          "url": "coil-compose-core-iosarm64-3.4.0-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 356,
          "sha512": "a9630fc03ba37083d99721a541c6e7f98c17c7d3e3a933feed78b29b45d089d6b1d3013f998dba211f528fc71fe4676e1bb5cf4d10ec2fe6df5c78852140043b",
          "sha256": "1fa005678b2bd0d08179b832348cc67cca094a844571c13b6705bfff394bee40",
          "sha1": "b573ed4279109cfa06c9e8187e672bb7a55635d4",
          "md5": "26f31c8dafa0bfd69022cde198b7e06d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-core-iosarm64-3.4.0-SNAPSHOT-metadata.jar",
          "url": "coil-compose-core-iosarm64-3.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
