{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-network-ktor3/3.4.0-SNAPSHOT/coil-network-ktor3-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-network-ktor3",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-okio",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-ktor3-linuxX64Main-3.4.0-SNAPSHOT.klib",
          "url": "coil-network-ktor3-linuxx64-3.4.0-SNAPSHOT.klib",
          "size": 18084,
          "sha512": "92866857bf923c04014e0cf7959fd2f7b6b24e8145007c6d9d97da18b8bcc8b54d772e12c8705d6de74eda14a1a6acdeadb96b235f01a92f755a9696b4c5593f",
          "sha256": "7ede2042998c991763debfc3b0b41df33a3c2a870b7dcf613b3e9a4b106b37e4",
          "sha1": "95a0ceaf507ad4244ad88eaebf4c26feda155493",
          "md5": "7140252511d8cf0dc91632398ae4e8f3"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "coil-network-ktor3-linuxx64-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-network-ktor3-linuxx64-3.4.0-SNAPSHOT-sources.jar",
          "size": 5165,
          "sha512": "8233cab609ea091b07b4df3ce6d0db3f82af76c0007df12a4327027b74c4f0d4c49db1629123352df9da4746504af1ad28c7f678ceecb9a5dd4e7732ae0fb46d",
          "sha256": "08030f0b37cb677df4237d370ef9378541d03e5c1a0835586c8b9ed2abc577e1",
          "sha1": "424018eef7617fd2848f53a50ab43d0fd8319650",
          "md5": "b860e8a73286c0a081dd9b3bdaf82362"
        }
      ]
    }
  ]
}
