{
  "formatVersion": "1.1",
  "component": {
    "group": "io.coil-kt.coil3",
    "module": "coil-network-cache-control",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-cache-control-metadata-3.4.0-SNAPSHOT.jar",
          "url": "coil-network-cache-control-3.4.0-SNAPSHOT.jar",
          "size": 4810,
          "sha512": "478285af1406e395002f7ef9cb7e3a6e0415b245fcaf1e4935060c53848512176c1715d11ad9fa9189b032a98112248d99d11aab44a7d69e68e35e16af64e35a",
          "sha256": "c0397011a02a361d293f3f7f2bf6d56b7ea14844ea6fb5776622eba034534474",
          "sha1": "dfaadfb210cc76a3ebf38cc300b1e245634a1f93",
          "md5": "305e4f5acc831d1cc3693032be836121"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "coil-network-cache-control-kotlin-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-network-cache-control-3.4.0-SNAPSHOT-sources.jar",
          "size": 8030,
          "sha512": "3163473ed56992cb1bcf3b57ccdb952243e8bcb4e005abddb4a2b861ac69d11965feb2803ea70b1b4a28447c173440be3b5c0226d29b2dcc6a32810bce81880f",
          "sha256": "bc0d4c05573187c53a32f0b31a05a73f5af734a576814d52b3e227e0b71ea9db",
          "sha1": "04fd04e781304ecc96559b93e6491444610fff61",
          "md5": "14aea17f3769973aa16124f84624a0fa"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-android/3.4.0-SNAPSHOT/coil-network-cache-control-android-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-android",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-android/3.4.0-SNAPSHOT/coil-network-cache-control-android-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-android",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-android/3.4.0-SNAPSHOT/coil-network-cache-control-android-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-android",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-iosarm64/3.4.0-SNAPSHOT/coil-network-cache-control-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-iosarm64/3.4.0-SNAPSHOT/coil-network-cache-control-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-iosarm64/3.4.0-SNAPSHOT/coil-network-cache-control-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-iossimulatorarm64/3.4.0-SNAPSHOT/coil-network-cache-control-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-iossimulatorarm64/3.4.0-SNAPSHOT/coil-network-cache-control-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-iossimulatorarm64/3.4.0-SNAPSHOT/coil-network-cache-control-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-iosx64/3.4.0-SNAPSHOT/coil-network-cache-control-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-iosx64/3.4.0-SNAPSHOT/coil-network-cache-control-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-iosx64/3.4.0-SNAPSHOT/coil-network-cache-control-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-js/3.4.0-SNAPSHOT/coil-network-cache-control-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-js/3.4.0-SNAPSHOT/coil-network-cache-control-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-js/3.4.0-SNAPSHOT/coil-network-cache-control-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-jvm/3.4.0-SNAPSHOT/coil-network-cache-control-jvm-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-jvm",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-jvm/3.4.0-SNAPSHOT/coil-network-cache-control-jvm-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-jvm",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-jvm/3.4.0-SNAPSHOT/coil-network-cache-control-jvm-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-jvm",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-linuxarm64/3.4.0-SNAPSHOT/coil-network-cache-control-linuxarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-linuxarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-linuxarm64/3.4.0-SNAPSHOT/coil-network-cache-control-linuxarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-linuxarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-linuxx64/3.4.0-SNAPSHOT/coil-network-cache-control-linuxx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-linuxx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-linuxx64/3.4.0-SNAPSHOT/coil-network-cache-control-linuxx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-linuxx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-macosarm64/3.4.0-SNAPSHOT/coil-network-cache-control-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-macosarm64/3.4.0-SNAPSHOT/coil-network-cache-control-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-macosarm64/3.4.0-SNAPSHOT/coil-network-cache-control-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-macosx64/3.4.0-SNAPSHOT/coil-network-cache-control-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-macosx64/3.4.0-SNAPSHOT/coil-network-cache-control-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-macosx64/3.4.0-SNAPSHOT/coil-network-cache-control-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-wasm-js/3.4.0-SNAPSHOT/coil-network-cache-control-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-wasm-js/3.4.0-SNAPSHOT/coil-network-cache-control-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-network-cache-control-wasm-js/3.4.0-SNAPSHOT/coil-network-cache-control-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-network-cache-control-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    }
  ]
}
