{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-test/3.4.0-SNAPSHOT/coil-test-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-test",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-test-linuxArm64Main-3.4.0-SNAPSHOT.klib",
          "url": "coil-test-linuxarm64-3.4.0-SNAPSHOT.klib",
          "size": 21718,
          "sha512": "8acb19aa611ba0326538a87f750dec305c670f42af86544c50a1c73d8dc328615e8db91dcbda6f29e757c36cada47f999783eb817dd62f1ac86b7a5e7ba2c901",
          "sha256": "8adde76d848d5cf817e9dca79fa3370bf8349d33730c0bdf25b611a1f2640d78",
          "sha1": "ab6e1960d588b78470fad243ec627e1406458a2d",
          "md5": "b3de9f02fe9b0ced4451fc9ed9ec46dc"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "coil-test-linuxarm64-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-test-linuxarm64-3.4.0-SNAPSHOT-sources.jar",
          "size": 5108,
          "sha512": "19f94c92c971c5f5f90699de2ad55f23817da5d9abe7d027f3b4fad8872cfd724cab04c365365a91d350a47ee8ddd90dbbb677ac0ebf8977d41a544d19e2d41f",
          "sha256": "dabc717837fe8b897f0ad526f47c097483983794c6b0b46eeec868ccfe2a7273",
          "sha1": "57c7336e8f2bdc8755a3e268d8ef8f583c6fc2ba",
          "md5": "d6f96fa2e4b4f245a158978c221434f1"
        }
      ]
    }
  ]
}
