{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-network-core/3.4.0-SNAPSHOT/coil-network-core-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-network-core",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-core-iosArm64Main-3.4.0-SNAPSHOT.klib",
          "url": "coil-network-core-iosarm64-3.4.0-SNAPSHOT.klib",
          "size": 57660,
          "sha512": "01ce1bf6b5a508fc8cae69d404dd25069eda6788d9fb682854a572bf2ebf03efa057382ef3bbd2e23c413787f642e9e1f062afcf0493bf052f87551aa5b3fa16",
          "sha256": "7aa7872f0ecb7f1d2c42f2a4b8d866c22cadf5e874a2e50fe1b1371bddd96de6",
          "sha1": "b0189a5bdb475102c557c55bb82e68dca6a4f433",
          "md5": "3d57406addd2d4850e34497927a91043"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "coil-network-core-iosarm64-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-network-core-iosarm64-3.4.0-SNAPSHOT-sources.jar",
          "size": 12216,
          "sha512": "8dd5765f642666e938ada828ff88f9647e3bb3cdc75406547c0a778313500274fe2dc572d8b636ef62b5e9e90242eb771ab50989a32b1936c2a96694555a7ea6",
          "sha256": "9b39dc835f2f8d7c6fd08619b1cd3328e130e01aedf583ad19c2b97888eb7935",
          "sha1": "4a2ddfc3e84a716218e63ef75b2b994e12fc3350",
          "md5": "b28124cf8eade53422542a4dbeeba485"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-core-iosarm64-3.4.0-SNAPSHOT-metadata.jar",
          "url": "coil-network-core-iosarm64-3.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
