{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-svg/3.4.0-SNAPSHOT/coil-svg-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-svg",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-svg-wasm-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-svg-wasm-js-3.4.0-SNAPSHOT.klib",
          "size": 3416629,
          "sha512": "750412bba715217d5136aac79470616c94cda73fb1c98a0c11ca86857ecadb1c09b195df241aec41730c7aa098f74e521d821c5bf617224a05b23e9c7b43a2df",
          "sha256": "c56ab8468f9d16d18343c3fbd8eb403011b1414e34012d3bf455123c3bc28cd6",
          "sha1": "c0e71eaf687f7291341f4e3095977c93f257d138",
          "md5": "765f2d17054da1ce682a70dc015c06d3"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.22.2"
          }
        }
      ],
      "files": [
        {
          "name": "coil-svg-wasm-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-svg-wasm-js-3.4.0-SNAPSHOT.klib",
          "size": 3416629,
          "sha512": "750412bba715217d5136aac79470616c94cda73fb1c98a0c11ca86857ecadb1c09b195df241aec41730c7aa098f74e521d821c5bf617224a05b23e9c7b43a2df",
          "sha256": "c56ab8468f9d16d18343c3fbd8eb403011b1414e34012d3bf455123c3bc28cd6",
          "sha1": "c0e71eaf687f7291341f4e3095977c93f257d138",
          "md5": "765f2d17054da1ce682a70dc015c06d3"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "coil-svg-wasm-js-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-svg-wasm-js-3.4.0-SNAPSHOT-sources.jar",
          "size": 9084,
          "sha512": "8f195d5dc0f5ca7d47e706ab0bd04321835990fe51ec9cff03161da8d979d42c0b5eda263156c00984b173337ec36834afa7035af3ff2c0a4db0e79072ef7ada",
          "sha256": "ac2563e53548c4d575e250f5f0070755c45160f9edf3b7b19e4c7265f47f205b",
          "sha1": "be73e7b57c600705aa02381cdea6e831c40d47a9",
          "md5": "f75102061a393b377a75df9109e2a67d"
        }
      ]
    }
  ]
}
