{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-network-cache-control/3.4.0-SNAPSHOT/coil-network-cache-control-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-network-cache-control",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-cache-control-linuxX64Main-3.4.0-SNAPSHOT.klib",
          "url": "coil-network-cache-control-linuxx64-3.4.0-SNAPSHOT.klib",
          "size": 32745,
          "sha512": "618c022dd64d1ce215e7588a0f76829dca4250e217ae4cf6cf9ac92b2a67a9a69ddb2c4d4cad7986fe5fd29f491624edf8fe1e415932a9ea0d64dd6874c028e4",
          "sha256": "1fa320f657aafbdaf20d30d724b8f130233601b5e65f2215abc3f78b9063ab00",
          "sha1": "69a705e09380bd4422ad410210185584473484e6",
          "md5": "8d2797a3fcc416cc134b13e6c1d068d7"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "coil-network-cache-control-linuxx64-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-network-cache-control-linuxx64-3.4.0-SNAPSHOT-sources.jar",
          "size": 8030,
          "sha512": "3163473ed56992cb1bcf3b57ccdb952243e8bcb4e005abddb4a2b861ac69d11965feb2803ea70b1b4a28447c173440be3b5c0226d29b2dcc6a32810bce81880f",
          "sha256": "bc0d4c05573187c53a32f0b31a05a73f5af734a576814d52b3e227e0b71ea9db",
          "sha1": "04fd04e781304ecc96559b93e6491444610fff61",
          "md5": "14aea17f3769973aa16124f84624a0fa"
        }
      ]
    }
  ]
}
