{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-web-decoder/3.4.0-SNAPSHOT/coil-web-decoder-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-web-decoder",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-web-decoder-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-web-decoder-js-3.4.0-SNAPSHOT.klib",
          "size": 3403349,
          "sha512": "5815b15830c103914ea53c1677e6a45c9090230a09e6427bbcfd1fe745a9bb02a4fe96734c1b6a2c964bdb3278add424e2818446a2a9552aaeac6903962e013d",
          "sha256": "675d7719b9e228ea50031384ba60483db0a5a41ec92d924a26780061ad06eeb4",
          "sha1": "8c8a2a7145461eb28aa40ef9452ce46d7e0bec86",
          "md5": "f253ec30e8aba74aee2179c4bb42a778"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "26.2.5-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "coil-web-decoder-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-web-decoder-js-3.4.0-SNAPSHOT.klib",
          "size": 3403349,
          "sha512": "5815b15830c103914ea53c1677e6a45c9090230a09e6427bbcfd1fe745a9bb02a4fe96734c1b6a2c964bdb3278add424e2818446a2a9552aaeac6903962e013d",
          "sha256": "675d7719b9e228ea50031384ba60483db0a5a41ec92d924a26780061ad06eeb4",
          "sha1": "8c8a2a7145461eb28aa40ef9452ce46d7e0bec86",
          "md5": "f253ec30e8aba74aee2179c4bb42a778"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "coil-web-decoder-js-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-web-decoder-js-3.4.0-SNAPSHOT-sources.jar",
          "size": 5729,
          "sha512": "040e309cfc2d313b88e77064d078932132353a24080dd2000214448f76b82d923d95b06c8f01240ab9a57169427bf22d845d167798e4367ba3e121bdac7a4fb8",
          "sha256": "44e118bca636d095cdbc2db2b72e62c84ba5d413fc48264cfa890b7d3c713cb7",
          "sha1": "9b05bf6b4e0fcc11218170049a3bf48caf60bc7e",
          "md5": "8feacf40f25e76a77a016142c6c635f5"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "26.2.5-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "coil-web-decoder-3.4.0-SNAPSHOT.kotlin_resources.zip",
          "url": "coil-web-decoder-js-3.4.0-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 1237,
          "sha512": "f7562f8945d6d4792c1e4dcbdc83b7588d42c81f0dbe07fa1ee3e19b31183db9846c2725da4b95a9e2ed89834f72f212be09239fa270d6e1acc64ff05a0cea65",
          "sha256": "14079e1ea0b00f3c44f9cfdc6121386c4aa0a5f414f40e6c05232c4ceb425ab1",
          "sha1": "0e8531c838a723a5b7db02d26641ba5b6bd0b716",
          "md5": "01c8a265e2db818838cdd369dcf776b9"
        }
      ]
    }
  ]
}
