{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-svg/3.4.0-SNAPSHOT/coil-svg-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-svg",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.22.2"
          }
        }
      ],
      "files": [
        {
          "name": "coil-svg-linuxX64Main-3.4.0-SNAPSHOT.klib",
          "url": "coil-svg-linuxx64-3.4.0-SNAPSHOT.klib",
          "size": 32526,
          "sha512": "b02b91341bd98150ed63791ca30abc40e3ecb6d3009ab198ad5b6f6e5d8e38462114141180872a67919af3afa0e14dfa5923cd88c4b466da77af1617380b6873",
          "sha256": "ca1c7ddd46b081f78ec30beb4bc19e23558a958fca53a06769226521bbbd5b79",
          "sha1": "7592b031d4572cd0a594fb663e83aa8822e8d504",
          "md5": "a696247c78b61b5d2e7668128b1d8d7e"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "coil-svg-linuxx64-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-svg-linuxx64-3.4.0-SNAPSHOT-sources.jar",
          "size": 9084,
          "sha512": "a100857002ea70d0858ad03a781a1ddae81986912320597c9cf39a4914dcc266678a6bef1ad185ff12750ceb3ba28874976757b4d68addfcc0c3c5b2a3dd3843",
          "sha256": "6fa9a8932aad56b11bf7c8f9ed40fed9ea6b2b6a2a4a45eedfb399122e7a77dc",
          "sha1": "75ee194f5f8834db20b9305cd0630c951c524e0d",
          "md5": "62326fd9f6b1f3db435c56c9fc9ef0f1"
        }
      ]
    }
  ]
}
