{
  "formatVersion": "1.1",
  "component": {
    "group": "io.coil-kt.coil3",
    "module": "coil-compose",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-metadata-3.4.0-SNAPSHOT.jar",
          "url": "coil-compose-3.4.0-SNAPSHOT.jar",
          "size": 4948,
          "sha512": "ba6d9f67aa860196eba52d7f4ce4768e003c649cf86031b966448a276bc7d5c5ee38236c661fd9e867b2fcadc6e3364f19df682cce4480a6017331f1a7e9ee43",
          "sha256": "3bcb0062622d91d9de89c05cddcd61ed78c2198726ae9984e7fb9abd33fef0e3",
          "sha1": "15d850d449c9191c6591ced3e786c98c079ee3c3",
          "md5": "f945db5217ceadaf695da9775de14e39"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "coil-compose-kotlin-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-compose-3.4.0-SNAPSHOT-sources.jar",
          "size": 5476,
          "sha512": "76f78fc8e21ba26fdfba4d78d66dfc3aa89d029798d19807718b8f4d0c62b7264e903bfc67e45d2cad11dab5ccefffec2fe01e9177edd4c21421fd29b9e20f2d",
          "sha256": "31174b39d8ac98c986533e3f82cc62a5be244fee3d44dcf00f249e7d1849650a",
          "sha1": "c0579e5ea19c4eedf6aa44379d0add2f7436ec73",
          "md5": "a43398b8e04292f126e5158abd6b3267"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-compose-android/3.4.0-SNAPSHOT/coil-compose-android-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-android",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-compose-android/3.4.0-SNAPSHOT/coil-compose-android-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-android",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-compose-android/3.4.0-SNAPSHOT/coil-compose-android-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-android",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-iosarm64/3.4.0-SNAPSHOT/coil-compose-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-iosarm64/3.4.0-SNAPSHOT/coil-compose-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-iosarm64/3.4.0-SNAPSHOT/coil-compose-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-iosarm64/3.4.0-SNAPSHOT/coil-compose-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-iossimulatorarm64/3.4.0-SNAPSHOT/coil-compose-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-iossimulatorarm64/3.4.0-SNAPSHOT/coil-compose-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-iossimulatorarm64/3.4.0-SNAPSHOT/coil-compose-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-iossimulatorarm64/3.4.0-SNAPSHOT/coil-compose-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-iosx64/3.4.0-SNAPSHOT/coil-compose-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-iosx64/3.4.0-SNAPSHOT/coil-compose-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-iosx64/3.4.0-SNAPSHOT/coil-compose-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-iosx64/3.4.0-SNAPSHOT/coil-compose-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-compose-js/3.4.0-SNAPSHOT/coil-compose-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-compose-js/3.4.0-SNAPSHOT/coil-compose-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-compose-js/3.4.0-SNAPSHOT/coil-compose-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-compose-js/3.4.0-SNAPSHOT/coil-compose-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-compose-jvm/3.4.0-SNAPSHOT/coil-compose-jvm-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-jvm",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-compose-jvm/3.4.0-SNAPSHOT/coil-compose-jvm-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-jvm",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-compose-jvm/3.4.0-SNAPSHOT/coil-compose-jvm-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-jvm",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-macosarm64/3.4.0-SNAPSHOT/coil-compose-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-macosarm64/3.4.0-SNAPSHOT/coil-compose-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-macosarm64/3.4.0-SNAPSHOT/coil-compose-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-macosarm64/3.4.0-SNAPSHOT/coil-compose-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-macosx64/3.4.0-SNAPSHOT/coil-compose-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-macosx64/3.4.0-SNAPSHOT/coil-compose-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-macosx64/3.4.0-SNAPSHOT/coil-compose-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-macosx64/3.4.0-SNAPSHOT/coil-compose-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-compose-wasm-js/3.4.0-SNAPSHOT/coil-compose-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-compose-wasm-js/3.4.0-SNAPSHOT/coil-compose-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-compose-wasm-js/3.4.0-SNAPSHOT/coil-compose-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-compose-wasm-js/3.4.0-SNAPSHOT/coil-compose-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    }
  ]
}
