{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-core/3.4.0-SNAPSHOT/coil-core-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-core",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.22.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-core-iosX64Main-3.4.0-SNAPSHOT.klib",
          "url": "coil-core-iosx64-3.4.0-SNAPSHOT.klib",
          "size": 377389,
          "sha512": "2f7ef68a72e972906d9c0b0a44dfea3db16c77106fe29e99563b0ca78f4152647a15306f0f708a5c39d7c211d103515aa108f80454a97d267960be5c30c5bc8e",
          "sha256": "99a9fc2ffe7635e2e9015f71e82d6693f3e600d361b9fe2fa1da007d2817d208",
          "sha1": "8b0524e88b44c619dc4c297b57e62dbea734b991",
          "md5": "4da21cbc4670522c9306fc23ffe09dff"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "coil-core-iosx64-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-core-iosx64-3.4.0-SNAPSHOT-sources.jar",
          "size": 89671,
          "sha512": "787b4dc8b1c43ca66809d4f454aeb97bc3ff26d900263524469c38dbb8fd7a445fc913a4bcbd542fdf2c0f00cfbf4684be43c3fd9b87576f7885c0758b6db183",
          "sha256": "62e106512f7ce69b8e86adfe5c8be3c94c37901093eb6f5f0b64f9aad553e151",
          "sha1": "d1f6fd1a95f8ada003c367396117a3b0cbafb004",
          "md5": "d040ae001da7422ec9c8bba6ef3239b8"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.22.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-core-iosx64-3.4.0-SNAPSHOT-metadata.jar",
          "url": "coil-core-iosx64-3.4.0-SNAPSHOT-metadata.jar",
          "size": 3230,
          "sha512": "a617fc43cdf90da099e9b61db486304a948a1bc911b6993fff7bf4b84cf4db9644faf619408c344ac10a7c3404759bae7636c9f73c3f9093deda89a79abc840e",
          "sha256": "c4130b000c0cd03e6ceda4ac9b16ee893a13afbdc66157fee44cf6e60014784e",
          "sha1": "cbd0fb3fd594e8df8b5e3da96a8c0d335bd96860",
          "md5": "2583984769410e631219fc32cc85fe5c"
        }
      ]
    }
  ]
}
