{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil/3.4.0-SNAPSHOT/coil-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-js-3.4.0-SNAPSHOT.klib",
          "size": 3394457,
          "sha512": "717be1128e50e60a443f731cd52c76edac4c1237c61e5fde0cade352dff5b5c16808a538dc4252a0c41e8e69b60b4eb5f920d1f7683c45c2850a5ce84064cd9f",
          "sha256": "7f35ce412a46157594fe1bd9d5bf9b2bc80396ab0b3026af18359ecd818e08f1",
          "sha1": "fe4631992cdac5f8e3f6c8d2592ef6656175e5ce",
          "md5": "cb100af2167e3cbe72d0b3171b73e2b6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-js-3.4.0-SNAPSHOT.klib",
          "size": 3394457,
          "sha512": "717be1128e50e60a443f731cd52c76edac4c1237c61e5fde0cade352dff5b5c16808a538dc4252a0c41e8e69b60b4eb5f920d1f7683c45c2850a5ce84064cd9f",
          "sha256": "7f35ce412a46157594fe1bd9d5bf9b2bc80396ab0b3026af18359ecd818e08f1",
          "sha1": "fe4631992cdac5f8e3f6c8d2592ef6656175e5ce",
          "md5": "cb100af2167e3cbe72d0b3171b73e2b6"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "coil-js-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-js-3.4.0-SNAPSHOT-sources.jar",
          "size": 2422,
          "sha512": "1b2c21550919e28e49987eca446d93cb0437747e9faa0ef498cc94095da08978134a938d40ff150175aa16aff2b482c05e744c25cbe1e15d83aea25512e24f3c",
          "sha256": "5cb583ff59b7ddcbfc8a765ab62c174475dfa2c292c25101073ec4ef77867ebd",
          "sha1": "c2e2eb9f948f34422b4ab1fdd782c2c1c1dcb468",
          "md5": "3a8989ae151f9cac0bc7d1c625025659"
        }
      ]
    }
  ]
}
