{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-compose/3.4.0-SNAPSHOT/coil-compose-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-compose",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-jvm-3.4.0-SNAPSHOT.jar",
          "url": "coil-compose-jvm-3.4.0-SNAPSHOT.jar",
          "size": 13930,
          "sha512": "d24a217d77c7ada41f2719d2867e4fe3c2bab6f2c6fc95f2512ac3876c61f1311502c1f4a94dc15f4a4f3e30246c6bc4d2ef14e2c9247455bb24b2afcf74b8a5",
          "sha256": "49ceedc003b5cf8d57d98426b552830e808036235a6909895e8b1866745c1a31",
          "sha1": "d7aa23afd3db28824e54edab1976d3b1bddbc583",
          "md5": "7da4ba19111fea4cdcfa7ad8e68252e3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-jvm-3.4.0-SNAPSHOT.jar",
          "url": "coil-compose-jvm-3.4.0-SNAPSHOT.jar",
          "size": 13930,
          "sha512": "d24a217d77c7ada41f2719d2867e4fe3c2bab6f2c6fc95f2512ac3876c61f1311502c1f4a94dc15f4a4f3e30246c6bc4d2ef14e2c9247455bb24b2afcf74b8a5",
          "sha256": "49ceedc003b5cf8d57d98426b552830e808036235a6909895e8b1866745c1a31",
          "sha1": "d7aa23afd3db28824e54edab1976d3b1bddbc583",
          "md5": "7da4ba19111fea4cdcfa7ad8e68252e3"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "coil-compose-jvm-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-compose-jvm-3.4.0-SNAPSHOT-sources.jar",
          "size": 5476,
          "sha512": "76f78fc8e21ba26fdfba4d78d66dfc3aa89d029798d19807718b8f4d0c62b7264e903bfc67e45d2cad11dab5ccefffec2fe01e9177edd4c21421fd29b9e20f2d",
          "sha256": "31174b39d8ac98c986533e3f82cc62a5be244fee3d44dcf00f249e7d1849650a",
          "sha1": "c0579e5ea19c4eedf6aa44379d0add2f7436ec73",
          "md5": "a43398b8e04292f126e5158abd6b3267"
        }
      ]
    }
  ]
}
