{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-network-okhttp/3.4.0-SNAPSHOT/coil-network-okhttp-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-network-okhttp",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-okhttp-jvm-3.4.0-SNAPSHOT.jar",
          "url": "coil-network-okhttp-jvm-3.4.0-SNAPSHOT.jar",
          "size": 22644,
          "sha512": "040fb7e63c46332d9e2b9f399752b74ad140f7aa452a002e3f6e25eeacc667ec3fdbb33d0e221d92f647f20ce703957b96bd43b511d1935eb3427b8e5df33d0b",
          "sha256": "c0b6e079044babb31fcbc6455983b05f455925cc8ff17ef94914bac6594ad6c0",
          "sha1": "135849d0e58ac353057d7cf5974e05143e7d3467",
          "md5": "b22ce6068044f5d020cdfdd7ac978cde"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-okhttp-jvm-3.4.0-SNAPSHOT.jar",
          "url": "coil-network-okhttp-jvm-3.4.0-SNAPSHOT.jar",
          "size": 22644,
          "sha512": "040fb7e63c46332d9e2b9f399752b74ad140f7aa452a002e3f6e25eeacc667ec3fdbb33d0e221d92f647f20ce703957b96bd43b511d1935eb3427b8e5df33d0b",
          "sha256": "c0b6e079044babb31fcbc6455983b05f455925cc8ff17ef94914bac6594ad6c0",
          "sha1": "135849d0e58ac353057d7cf5974e05143e7d3467",
          "md5": "b22ce6068044f5d020cdfdd7ac978cde"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "coil-network-okhttp-jvm-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-network-okhttp-jvm-3.4.0-SNAPSHOT-sources.jar",
          "size": 3979,
          "sha512": "0efe6523fce7d7da05b3e4a1e51e8d6935040ed281256edf1ce5e7dc79760e5f96affcf755e19e0059630ef41529a3c3b5963b2e17245b820346c7c23c8a57d0",
          "sha256": "b830dce53f1a459eb3ccc44b302595342cb8d3cc1f09a255fcd04242193dc973",
          "sha1": "fa75d1809990dfe728ec59f958c72a8960efff5a",
          "md5": "5e9ddbb4d6b45783451df2ab9480441e"
        }
      ]
    }
  ]
}
