{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-compose-core/3.4.0-SNAPSHOT/coil-compose-core-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-compose-core",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-core-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-compose-core-js-3.4.0-SNAPSHOT.klib",
          "size": 3535365,
          "sha512": "b2d8d41b3b98c972c6c5ea4b1a8c69b27170efb5471d88d17b11f2d0277e78150df0c15fcb20d2bf402fd0dfbeba8ff0866ed319330101581f56d41c30b8ab08",
          "sha256": "f1d754f6965951c51935968ebdbc63fae3b1557e461afdc2d83fd9451802a49a",
          "sha1": "1b3d22c5ba113110744de5c90a824045ee75e027",
          "md5": "4b203af6dd1d1bb01bd246484846a033"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-core-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-compose-core-js-3.4.0-SNAPSHOT.klib",
          "size": 3535365,
          "sha512": "b2d8d41b3b98c972c6c5ea4b1a8c69b27170efb5471d88d17b11f2d0277e78150df0c15fcb20d2bf402fd0dfbeba8ff0866ed319330101581f56d41c30b8ab08",
          "sha256": "f1d754f6965951c51935968ebdbc63fae3b1557e461afdc2d83fd9451802a49a",
          "sha1": "1b3d22c5ba113110744de5c90a824045ee75e027",
          "md5": "4b203af6dd1d1bb01bd246484846a033"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "coil-compose-core-js-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-compose-core-js-3.4.0-SNAPSHOT-sources.jar",
          "size": 26307,
          "sha512": "16318c4080d8e72489d108f8451b01a802547e1b3bf2a6ce8e167004a441d7100b90f8d85bbee0c96346f8c94eeb4f292c7ff41186a242ef4741e63058a3472e",
          "sha256": "1197a1d8da6444937acdc166825bc8fecd4f1834238706469019b6ad023c0a64",
          "sha1": "3c767bc9c24ad6da7c7cbd61cb21a4eabc5e8169",
          "md5": "d711e9e948bae7fc8078feb809a0b611"
        }
      ]
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-core-3.4.0-SNAPSHOT.kotlin_resources.zip",
          "url": "coil-compose-core-js-3.4.0-SNAPSHOT-kotlin_resources.kotlin_resources.zip",
          "size": 356,
          "sha512": "a9630fc03ba37083d99721a541c6e7f98c17c7d3e3a933feed78b29b45d089d6b1d3013f998dba211f528fc71fe4676e1bb5cf4d10ec2fe6df5c78852140043b",
          "sha256": "1fa005678b2bd0d08179b832348cc67cca094a844571c13b6705bfff394bee40",
          "sha1": "b573ed4279109cfa06c9e8187e672bb7a55635d4",
          "md5": "26f31c8dafa0bfd69022cde198b7e06d"
        }
      ]
    }
  ]
}
