{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil/3.4.0-SNAPSHOT/coil-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-linuxArm64Main-3.4.0-SNAPSHOT.klib",
          "url": "coil-linuxarm64-3.4.0-SNAPSHOT.klib",
          "size": 11331,
          "sha512": "e4ec2303fb3a160c761fa12869eca420dda966f17d0730e769e9f8f5f2dbc51a1958caca5703c62575ccaa78dff77d68771d6e7274b9899d9a4dbee75b2372c6",
          "sha256": "b3d724a37bea625821266fa65e8ee67c31ebd41ca9ecc3d15ff42f4ccd92026d",
          "sha1": "bcf36f8d0a8435209f9fa627e1c0099e7f6e3e57",
          "md5": "46727b6a70af52f68c0f84e667869ff8"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "coil-linuxarm64-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-linuxarm64-3.4.0-SNAPSHOT-sources.jar",
          "size": 2422,
          "sha512": "1b2c21550919e28e49987eca446d93cb0437747e9faa0ef498cc94095da08978134a938d40ff150175aa16aff2b482c05e744c25cbe1e15d83aea25512e24f3c",
          "sha256": "5cb583ff59b7ddcbfc8a765ab62c174475dfa2c292c25101073ec4ef77867ebd",
          "sha1": "c2e2eb9f948f34422b4ab1fdd782c2c1c1dcb468",
          "md5": "3a8989ae151f9cac0bc7d1c625025659"
        }
      ]
    }
  ]
}
