{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil/3.4.0-SNAPSHOT/coil-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-jvm-3.4.0-SNAPSHOT.jar",
          "url": "coil-jvm-3.4.0-SNAPSHOT.jar",
          "size": 5918,
          "sha512": "fa749dbbdaada27da471c162b3c3fc7064c5066dd8ca8a397ab3c3c74800dc08ac7c3344ddc0a1820f49fe8f8dc6accffae166c4c43d04469c72d51ee119b46f",
          "sha256": "2c9a28725a5bd85afd3f393a04ecc77eace086213fd9f92257085761e5bc53af",
          "sha1": "e64272a5eae2ea0822f722b6b835df458c6950ab",
          "md5": "9c3c8bf4926f0ba006936382cdd33626"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-jvm-3.4.0-SNAPSHOT.jar",
          "url": "coil-jvm-3.4.0-SNAPSHOT.jar",
          "size": 5918,
          "sha512": "fa749dbbdaada27da471c162b3c3fc7064c5066dd8ca8a397ab3c3c74800dc08ac7c3344ddc0a1820f49fe8f8dc6accffae166c4c43d04469c72d51ee119b46f",
          "sha256": "2c9a28725a5bd85afd3f393a04ecc77eace086213fd9f92257085761e5bc53af",
          "sha1": "e64272a5eae2ea0822f722b6b835df458c6950ab",
          "md5": "9c3c8bf4926f0ba006936382cdd33626"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "coil-jvm-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-jvm-3.4.0-SNAPSHOT-sources.jar",
          "size": 2422,
          "sha512": "1b2c21550919e28e49987eca446d93cb0437747e9faa0ef498cc94095da08978134a938d40ff150175aa16aff2b482c05e744c25cbe1e15d83aea25512e24f3c",
          "sha256": "5cb583ff59b7ddcbfc8a765ab62c174475dfa2c292c25101073ec4ef77867ebd",
          "sha1": "c2e2eb9f948f34422b4ab1fdd782c2c1c1dcb468",
          "md5": "3a8989ae151f9cac0bc7d1c625025659"
        }
      ]
    }
  ]
}
