{
  "formatVersion": "1.1",
  "component": {
    "group": "io.coil-kt.coil3",
    "module": "coil-compose-core",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-compose-core-metadata-3.4.0-SNAPSHOT.jar",
          "url": "coil-compose-core-3.4.0-SNAPSHOT.jar",
          "size": 20317,
          "sha512": "51e76e0e0e06cc3d1d621fa97dcaf81f2530159aa63ca29d229e80522cdeba641dfbe2648039b3649b4f42e9c311eb19903a631badf37520af5c7bd1fe0dd93b",
          "sha256": "46397ede7981fdeb833a00e2eabb31b3567ca814cf670d754d11893473b4faa2",
          "sha1": "d5522fc749742cc6adf7879970db6f472dd945aa",
          "md5": "3049259a670b4255788b1638298c6f0e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "coil-compose-core-kotlin-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-compose-core-3.4.0-SNAPSHOT-sources.jar",
          "size": 26307,
          "sha512": "d2ad340615a11bf2eee03b27b9df4a64d16cde7a87f9ae0f0bde0c4b1dc99c2093875683096eff82bab23f9096300f78dba4d22f03fef01460c06c49bab34446",
          "sha256": "ebb114560b048596955850ddac7d6a9b3a5e7960d547a08ea29ff63d6980f435",
          "sha1": "3a27a80bbec5833f99266eadf2e6331ea8c03b62",
          "md5": "24ba5bfdaca33392397a876ede2b7554"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-compose-core-android/3.4.0-SNAPSHOT/coil-compose-core-android-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-android",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-compose-core-android/3.4.0-SNAPSHOT/coil-compose-core-android-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-android",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../coil-compose-core-android/3.4.0-SNAPSHOT/coil-compose-core-android-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-android",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosarm64/3.4.0-SNAPSHOT/coil-compose-core-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosarm64/3.4.0-SNAPSHOT/coil-compose-core-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosarm64/3.4.0-SNAPSHOT/coil-compose-core-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosarm64/3.4.0-SNAPSHOT/coil-compose-core-iosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iossimulatorarm64/3.4.0-SNAPSHOT/coil-compose-core-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iossimulatorarm64/3.4.0-SNAPSHOT/coil-compose-core-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iossimulatorarm64/3.4.0-SNAPSHOT/coil-compose-core-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iossimulatorarm64/3.4.0-SNAPSHOT/coil-compose-core-iossimulatorarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iossimulatorarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosx64/3.4.0-SNAPSHOT/coil-compose-core-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosx64/3.4.0-SNAPSHOT/coil-compose-core-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosx64/3.4.0-SNAPSHOT/coil-compose-core-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-iosx64/3.4.0-SNAPSHOT/coil-compose-core-iosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-iosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-js/3.4.0-SNAPSHOT/coil-compose-core-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-js/3.4.0-SNAPSHOT/coil-compose-core-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-js/3.4.0-SNAPSHOT/coil-compose-core-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-js/3.4.0-SNAPSHOT/coil-compose-core-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-compose-core-jvm/3.4.0-SNAPSHOT/coil-compose-core-jvm-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-jvm",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-compose-core-jvm/3.4.0-SNAPSHOT/coil-compose-core-jvm-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-jvm",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coil-compose-core-jvm/3.4.0-SNAPSHOT/coil-compose-core-jvm-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-jvm",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosarm64/3.4.0-SNAPSHOT/coil-compose-core-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosarm64/3.4.0-SNAPSHOT/coil-compose-core-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosarm64/3.4.0-SNAPSHOT/coil-compose-core-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosarm64/3.4.0-SNAPSHOT/coil-compose-core-macosarm64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosarm64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosx64/3.4.0-SNAPSHOT/coil-compose-core-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosx64/3.4.0-SNAPSHOT/coil-compose-core-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosx64/3.4.0-SNAPSHOT/coil-compose-core-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coil-compose-core-macosx64/3.4.0-SNAPSHOT/coil-compose-core-macosx64-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-macosx64",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-wasm-js/3.4.0-SNAPSHOT/coil-compose-core-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-wasm-js/3.4.0-SNAPSHOT/coil-compose-core-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-wasm-js/3.4.0-SNAPSHOT/coil-compose-core-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../coil-compose-core-wasm-js/3.4.0-SNAPSHOT/coil-compose-core-wasm-js-3.4.0-SNAPSHOT.module",
        "group": "io.coil-kt.coil3",
        "module": "coil-compose-core-wasm-js",
        "version": "3.4.0-SNAPSHOT"
      }
    }
  ]
}
