{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-network-ktor2/3.4.0-SNAPSHOT/coil-network-ktor2-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-network-ktor2",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-ktor2-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-network-ktor2-js-3.4.0-SNAPSHOT.klib",
          "size": 3404382,
          "sha512": "2912fe6c4bad2fb59dfc14fc3c0c5be1d10496970b8e358feb73b7f9e4366d06b3fba8dca37cd7b4ebd05d6ec2e0832701da8e97dfb0be4c3debd6f2dcd7227d",
          "sha256": "eeb1e18cf087204ea8558159beb4c6d6257c7b445a81fd0992ef5f05a6547f98",
          "sha1": "040fd05afbdb23db6fa19442a3fe55c07cf60bc7",
          "md5": "928d681c36c2dbc0cbab4e016c198efb"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlinx-atomicfu-runtime",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "coil-network-ktor2-js-3.4.0-SNAPSHOT.klib",
          "url": "coil-network-ktor2-js-3.4.0-SNAPSHOT.klib",
          "size": 3404382,
          "sha512": "2912fe6c4bad2fb59dfc14fc3c0c5be1d10496970b8e358feb73b7f9e4366d06b3fba8dca37cd7b4ebd05d6ec2e0832701da8e97dfb0be4c3debd6f2dcd7227d",
          "sha256": "eeb1e18cf087204ea8558159beb4c6d6257c7b445a81fd0992ef5f05a6547f98",
          "sha1": "040fd05afbdb23db6fa19442a3fe55c07cf60bc7",
          "md5": "928d681c36c2dbc0cbab4e016c198efb"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "coil-network-ktor2-js-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-network-ktor2-js-3.4.0-SNAPSHOT-sources.jar",
          "size": 5271,
          "sha512": "01c0852cfc803402c723ac3c5c11d1bab0869ce9f9f520ce0e1be67cd4cdf90b0dad1b6251089f33c4dc4fd4df5ffae46da6fd3db938ddd4f974b0fc49191992",
          "sha256": "4ddf8189fc401ee34c93cf0b57c557888bfca5f4d132f8a89fbb315eff94a6ab",
          "sha1": "0130d63e62f5552bcb13f5c7847be4a2c63a4b33",
          "md5": "5931b3fc75788f1b2450111faf703101"
        }
      ]
    }
  ]
}
