{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coil-svg/3.4.0-SNAPSHOT/coil-svg-3.4.0-SNAPSHOT.module",
    "group": "io.coil-kt.coil3",
    "module": "coil-svg",
    "version": "3.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.22.2"
          }
        }
      ],
      "files": [
        {
          "name": "coil-svg-iosX64Main-3.4.0-SNAPSHOT.klib",
          "url": "coil-svg-iosx64-3.4.0-SNAPSHOT.klib",
          "size": 32520,
          "sha512": "2e739d9de42c44e5f3adc7543e514d6db77b3d3ba7d31fb8570d130ec472d02c61d1ac501395bc0b2543838c9b18fb83d998e49bf1a3416f2d0e254f1c53e49e",
          "sha256": "2c1fc1117c6e464f94d764dc4d0f00dc53e7ff9d038de12e7141031df0acaa45",
          "sha1": "1716254738e69ff73fd6ca4b10a5499d8f7896e7",
          "md5": "885d0533f3cd97d1f65893ffb560f05f"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "coil-svg-iosx64-3.4.0-SNAPSHOT-sources.jar",
          "url": "coil-svg-iosx64-3.4.0-SNAPSHOT-sources.jar",
          "size": 9084,
          "sha512": "a100857002ea70d0858ad03a781a1ddae81986912320597c9cf39a4914dcc266678a6bef1ad185ff12750ceb3ba28874976757b4d68addfcc0c3c5b2a3dd3843",
          "sha256": "6fa9a8932aad56b11bf7c8f9ed40fed9ea6b2b6a2a4a45eedfb399122e7a77dc",
          "sha1": "75ee194f5f8834db20b9305cd0630c951c524e0d",
          "md5": "62326fd9f6b1f3db435c56c9fc9ef0f1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.31.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-core",
          "version": {
            "requires": "3.4.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.9.22.2"
          }
        }
      ],
      "files": [
        {
          "name": "coil-svg-iosx64-3.4.0-SNAPSHOT-metadata.jar",
          "url": "coil-svg-iosx64-3.4.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
